[package]
name = "fw16-kblight-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
num_enum = "0.7.5"
qmk-via-api = { version = "0.5.0", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
